sudo: false
language: node_js
node_js:
  - "lts/*"
matrix:
  fast_finish: true
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - ANGULAR_BUILD_TELEMETRY_OPTOUT: 1
os:
  - linux
  - osx
osx_image: xcode9.2
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
cache:
  directories:
    - ./node_modules
