sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - ANGULAR_BUILD_TELEMETRY_OPTOUT: 1
branches:
  only:
    - master
before_install:
  - ln -s /usr/bin/nodejs /usr/bin/node
  - npm install -g @bizappframework/angular-build
install:
  - npm install
  - npm link @bizappframework/angular-build
script:
  - npm run build
cache:
  directories:
    - ./node_modules
